---
version: 1.0
build_arg_defaults: 
  EE_BASE_IMAGE: 'hub.lab.example.com/ee-minimal-rhel8'
  EE_BUILDER_IMAGE: 'hub.lab.example.com/ansible-builder-rhel8'
 
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
